### ISSUE TITLE
Comments on reading the code

### ISSUE THREAD

**Issue by picanumber** [SuperV1234/meetingcpp2015#1]
Looks like Hana is being extremely influential with respect to modern metaprogramming (taking into account the time it's been around). I like this project, so I did a good reading of the code, here are some remarks and questions (in case you'd be interested): 
1. You are introducing 
   
   ```
   template <bool TX>
   using bool_ = std::integral_constant<bool, TX>;
   ```
   
   wouldn't the use of `std::bool_constant` suffice ? (it's the exact same thing)
2. Regarding the `FWD` macro: Why the `__VA_ARGS__` ? I mean the pack expansion operator is needed anyway for variadic forwarded arguments and I can't think of a case where you'd pass **two or more** distinct objects to `FWD` (or what such an action would mean). I've been using a simpler similar macro  [here](https://github.com/picanumber/CODEine/blob/master/benchmark.h) (called `fw`) that accepts a single parameter and variadic argument forwarding works the same way : 
   
   ```
   #define fw(what) std::forward<decltype(what)>(what)
   fun(fw(args)...); 
   ```
3. Is the function call operator needed in `static_if_result` ? It's obvious this example does not use it, (compiles without it plus `static_if_result` is an implementation detail, not visible by the user and not used by the implementation) but what was the intent in adding it ? 
4. Do you believe this way of programming offers advantages over tag dispatching? (I mean the library solution(s) available, not the syntax in the proposals - that's a different beast). Myself I'm a bit skeptic on the readability of the end product as this no a "hidden" functionality, one would have to skim through the "compile branches" (`if.then..`) with every day code (it's so cool though). 
5. If I were to pass function objects (instead of lambdas) this would work with C++ 03 (minus the forwarding) ... provided that we could replace the variable templates. Any ideas?

**Comment by vittorioromeo** [comment]
Hey @picanumber, thank you for the feedback.
1. `std::bool_constant` was introduced in C++17, that's why I did not use it.
2. `__VA_ARGS__` is used to make sure that symbols composed of multiple tokens, separated by commas, are handled as a single entity. (Example: templated values/function calls.)
3. Maybe I didn't understand your comment, but I don't see how it could work without `static_if_result::operator()`. `static_if_result` is returned as soon as a matching branch is found - the user-specified arguments in the call at the end of `static_if` are passed to `static_if_result` thanks to its `operator()`.
4. I think it's convenient syntactic sugar for localized, small compile-time branches. It is not a replacement for specialization. Check the proposed papers and the reddit links for examples and more discussion.
5. Hmm... I haven't tried it. You can replace the lambdas with function objects (with templated `operator()`). You can replace `bool_v` with an instance of `std::integral_constant`. It probably could work, but it would be so verbose that it would make no sense using it over specialization.

**Comment by picanumber** [comment]
1. To quote Rowan Attkinson "... but now that we have the recipe" :P
2. fair enough (you'd mean tuples etc, that's a good point)
3. You can see [here](http://coliru.stacked-crooked.com/a/04d9a72199ca308f) that if we comment out the operator everything works ;) This happens because a (public) function call operator is available in the base class, and that's what gets called (it also has one less level of indirection)

**Comment by vittorioromeo** [comment]
Oh I see it now, I feel stupid! Yeah, it is unnecessary since inheritance is being used. I will update the code as soon as I get home.

I think I implemented my own call operator because I was storing the callable as a class field instead of using inheritance in a previous implementation.

**Comment by vittorioromeo** [comment]
I updated the code both here and in the vrm::core library. Thanks!
